In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

In [3]:
df=pd.read_csv(r'C:\Users\pc\OneDrive\Documents\ML\online_food_delivery_dataset.csv')
df.head()

,Order_ID,Order_Date,City,Restaurant_Name,Cuisine_Type,Order_Amount,Discount_Applied,Discount_Amount,Final_Amount,Payment_Method,Delivery_Time_Minutes,Distance_km,Rider_Rating,Customer_Rating,Order_Status
0,ORD1,2026-02-22,Mumbai,Spice Hub,Italian,842.90,Yes,0.0,842.90,Card,107,6.32,4.4,3.8,Delivered
1,ORD2,2026-02-22,Pune,Curry Kingdom,Indian,974.79,Yes,50.0,924.79,UPI,101,2.68,4.7,3.8,Cancelled
2,ORD3,2026-02-22,Hyderabad,Sushi Spot,Chinese,1459.93,NaN,0.0,1459.93,Card,36,2.64,4.3,4.8,Cancelled
3,ORD4,2026-02-22,Chennai,Sushi Spot,Italian,151.44,Yes,100.0,51.44,Cash,74,6.32,3.3,3.6,Delivered
4,ORD5,2026-02-22,Delhi,Burger Town,Indian,949.10,Yes,0.0,949.10,Card,63,16.22,3.5,2.1,Delayed

In [4]:
df.shape

(2000, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               2000 non-null   object
 1   Order_Date             2000 non-null   object
 2   City                   2000 non-null   object
 3   Restaurant_Name        2000 non-null   object
 4   Cuisine_Type           2000 non-null   object
 5   Order_Amount           2000 non-null   float64
 6   Discount_Applied       1308 non-null   object
 7   Discount_Amount        1602 non-null   float64
 8   Final_Amount           2000 non-null   float64
 9   Payment_Method         2000 non-null   object
 10  Delivery_Time_Minutes  2000 non-null   int64
 11  Distance_km            2000 non-null   float64
 12  Rider_Rating           2000 non-null   float64
 13  Customer_Rating        2000 non-null   float64
 14  Order_Status           2000 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 234.5+ KB

In [7]:
df.isna().mean()*100

Order_ID                  0.0
Order_Date                0.0
City                      0.0
Restaurant_Name           0.0
Cuisine_Type              0.0
Order_Amount              0.0
Discount_Applied         34.6
Discount_Amount          19.9
Final_Amount              0.0
Payment_Method            0.0
Delivery_Time_Minutes     0.0
Distance_km               0.0
Rider_Rating              0.0
Customer_Rating           0.0
Order_Status              0.0
dtype: float64

In [8]:
df["Discount_Applied"]=df["Discount_Applied"].fillna(df["Discount_Applied"].mode()[0])

In [9]:
df.isnull().sum()

Order_ID                   0
Order_Date                 0
City                       0
Restaurant_Name            0
Cuisine_Type               0
Order_Amount               0
Discount_Applied           0
Discount_Amount          398
Final_Amount               0
Payment_Method             0
Delivery_Time_Minutes      0
Distance_km                0
Rider_Rating               0
Customer_Rating            0
Order_Status               0
dtype: int64

In [10]:
df["Discount_Amount"].skew()

np.float64(0.03352813227963141)

In [11]:
df["Discount_Amount"]=df["Discount_Amount"].fillna(df["Discount_Amount"].mean())

In [12]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
City                     0
Restaurant_Name          0
Cuisine_Type             0
Order_Amount             0
Discount_Applied         0
Discount_Amount          0
Final_Amount             0
Payment_Method           0
Delivery_Time_Minutes    0
Distance_km              0
Rider_Rating             0
Customer_Rating          0
Order_Status             0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
a=df.select_dtypes(include=np.number)

In [15]:
for i in a:
    q1=a[i].quantile(0.25)
    q2=a[i].quantile(0.50)
    q3=a[i].quantile(0.75)
    IQR=q3-q1
    UW=q3+1.5*IQR
    LW=q1-1.5*IQR
    outliers=((a[i]<LW))
    print(f"outliers present in{i} columns:",outliers.sum())

outliers present inOrder_Amount columns: 0
outliers present inDiscount_Amount columns: 0
outliers present inFinal_Amount columns: 0
outliers present inDelivery_Time_Minutes columns: 0
outliers present inDistance_km columns: 0
outliers present inRider_Rating columns: 0
outliers present inCustomer_Rating columns: 0

## Data Cleaning

In [16]:
df.head()

,Order_ID,Order_Date,City,Restaurant_Name,Cuisine_Type,Order_Amount,Discount_Applied,Discount_Amount,Final_Amount,Payment_Method,Delivery_Time_Minutes,Distance_km,Rider_Rating,Customer_Rating,Order_Status
0,ORD1,2026-02-22,Mumbai,Spice Hub,Italian,842.90,Yes,0.0,842.90,Card,107,6.32,4.4,3.8,Delivered
1,ORD2,2026-02-22,Pune,Curry Kingdom,Indian,974.79,Yes,50.0,924.79,UPI,101,2.68,4.7,3.8,Cancelled
2,ORD3,2026-02-22,Hyderabad,Sushi Spot,Chinese,1459.93,Yes,0.0,1459.93,Card,36,2.64,4.3,4.8,Cancelled
3,ORD4,2026-02-22,Chennai,Sushi Spot,Italian,151.44,Yes,100.0,51.44,Cash,74,6.32,3.3,3.6,Delivered
4,ORD5,2026-02-22,Delhi,Burger Town,Indian,949.10,Yes,0.0,949.10,Card,63,16.22,3.5,2.1,Delayed

In [22]:
df['Cuisine_Type'].value_counts()

Cuisine_Type
Italian      414
Chinese      413
Fast Food    398
Japanese     393
Indian       382
Name: count, dtype: int64

In [18]:
a=pd.DataFrame(df.groupby("Cuisine_Type")["Order_ID"].count().sort_values(ascending=False))
a.to_csv("Cuisine_order")

In [19]:
a

              Order_ID
Cuisine_Type
Italian            414
Chinese            413
Fast Food          398
Japanese           393
Indian             382

In [23]:
b=pd.DataFrame(df.groupby("Payment_Method")["Order_ID"].count().sort_values(ascending=False))
b.to_csv("Payment_order")
b

                Order_ID
Payment_Method
Wallet               519
UPI                  496
Card                 494
Cash                 491

In [24]:
c=pd.DataFrame(df.groupby("City")["Order_ID"].count().sort_values(ascending=False))
c.to_csv("City_order")
c

           Order_ID
City
Chennai         366
Bangalore       349
Pune            333
Delhi           330
Mumbai          321
Hyderabad       301

In [25]:
d=pd.DataFrame(df.groupby("Order_Status")["Order_ID"].count().sort_values(ascending=False))
d.to_csv("Order_status")
d

              Order_ID
Order_Status
Cancelled          675
Delivered          665
Delayed            660

In [26]:
df.groupby("Discount_Applied")["Order_ID"].count().sort_values(ascending=False)

Discount_Applied
Yes    1347
No      653
Name: Order_ID, dtype: int64

In [27]:
e=pd.DataFrame(df.groupby("Restaurant_Name")["Customer_Rating"].mean().sort_values(ascending=False))
e.to_csv("Average_rating")
e

                 Customer_Rating
Restaurant_Name
Biryani House           3.550397
Spice Hub               3.546614
Urban Tandoor           3.529918
Pizza Palace            3.501103
Curry Kingdom           3.489558
Food Factory            3.466245
Sushi Spot              3.445627
Burger Town             3.431897

In [28]:
f=pd.DataFrame(df.groupby("Restaurant_Name")["Final_Amount"].mean().sort_values(ascending=False))
f.to_csv("Average_amount")
f

                 Final_Amount
Restaurant_Name
Urban Tandoor     1089.156189
Burger Town       1071.727284
Biryani House     1065.749048
Spice Hub         1035.904661
Food Factory      1006.178734
Pizza Palace      1000.136654
Sushi Spot         989.850837
Curry Kingdom      963.733855

In [29]:
import os

In [30]:
os.getcwd()

'C:\\Users\\pc\\Internship(Teks)'